stages:
  - pre-build
  - build
  - test
  - analyze
  - deploy

variables:
  MAVEN_IMAGE: "maven:3.8.7-openjdk-18"
  MAVEN_CLI_OPTS: "-B -Dmaven.test.failure.ignore=false"  # Set to not ignore test failures
  MAVEN_CACHE_DIR: ".m2/repository"
  NEXUS_URL: "${Nexus_REPO_URL}"
  NEXUS_USER: "${Nexus_REPO_USER}" 
  NEXUS_PASSWORD: "${Nexus_REPO_PASS}"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  SONAR_PROJECT_KEY: "${SONAR_PROJECT_KEY}"
  GIT_DEPTH: "0"

cache:
  paths:
    - $MAVEN_CACHE_DIR

pre-build-analysis:
  stage: pre-build
  image: $MAVEN_IMAGE
  variables:
    MAVEN_OPTS: "-Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.token=${SONAR_TOKEN}"
  script:
    - ./mvnw -e -X sonar:sonar -DskipTests=true -Dsonar.java.binaries=.
  allow_failure: false

build:
  stage: build
  image: $MAVEN_IMAGE
  script:
    - echo "Building the project"
    - echo "JAVA_HOME is $JAVA_HOME"
    - ./mvnw -e -X $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week

test:
  stage: test
  image: $MAVEN_IMAGE
  script:
    - echo "Running tests"
    - ./mvnw -e -X $MAVEN_CLI_OPTS test
  dependencies:
    - build
  artifacts:
    paths:
      - target/surefire-reports
    reports:
      junit: target/surefire-reports/*.xml
    expire_in: 2 week

analyze:
  stage: analyze
  image: maven:3-eclipse-temurin-17
  variables:
    MAVEN_OPTS: "-Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.token=${SONAR_TOKEN}"
  script:
    - ./mvnw $MAVEN_CLI_OPTS clean install
    - echo "Running SonarQube analysis"
    - ls target/classes
    - ./mvnw $MAVEN_CLI_OPTS -X sonar:sonar -Dsonar.java.binaries=target/classes
  dependencies:
    - build

deploy:
  stage: deploy
  image: curlimages/curl:latest
  script:
    - echo "Deploying artifacts to Nexus"
    - |
      curl -v -u $NEXUS_USER:$NEXUS_PASSWORD \
        --upload-file target/*.jar \
        "$NEXUS_URL/$(basename target/*.jar)"
  dependencies:
    - build
  only:
    - master
