stages:
  - build
  - test
  - analyze
  - deploy

variables:
  MAVEN_IMAGE: "maven:3.8.7-openjdk-18"
  MAVEN_CLI_OPTS: "-B -Dmaven.test.failure.ignore=true"
  MAVEN_CACHE_DIR: ".m2/repository"
  NEXUS_URL: "${Nexus_REPO_URL}"
  NEXUS_USER: "${Nexus_REPO_USER}" 
  NEXUS_PASSWORD: "${Nexus_REPO_PASS}"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"

cache:
  paths:
    - $MAVEN_CACHE_DIR

build:
  stage: build
  image: $MAVEN_IMAGE
  script:
    - echo "Building the project"
    - echo "JAVA_HOME is $JAVA_HOME"
    - ./mvnw $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week

test:
  stage: test
  image: $MAVEN_IMAGE
  script:
    - echo "Running tests"
    - ./mvnw $MAVEN_CLI_OPTS test
  dependencies:
    - build
  artifacts:
    paths:
      - target/surefire-reports
    reports:
      junit: target/surefire-reports/*.xml
    expire_in: 1 week

analyze:
  stage: analyze
  image: maven:3-eclipse-temurin-17
  script:
    - echo "Running SonarQube analysis"
    - mvn sonar:sonar -Dsonar.projectKey=${SONAR_TOKEN} -Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.java.binaries=build/classes/java/main
  dependencies:
    - build

deploy:
  stage: deploy
  image: curlimages/curl:latest
  script:
    - echo "Deploying artifacts to Nexus"
    - |
      curl -u $NEXUS_USER:$NEXUS_PASSWORD \
        --upload-file target/*.jar \
        "$NEXUS_URL/$(basename target/*.jar)"
  dependencies:
    - build
  only:
    - master
