services:
  postgres:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_DB: parkinglot_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: endava123
    ports:
      - "5432:5432"
    volumes:
      - /pgdata:/var/lib/postgresql/data

  rabbitmq:
    hostname: rabbitmq
    container_name: rabbit-mq
    ports:
        - 15672:15672
        - 5672:5672
    image: rabbitmq:3-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data: